-- SQL Script om KOSTSRT codes te vinden in Firebird
-- Gebruik dit in DBeaver

-- 1. Bekijk alle KOSTSRT records met codes die beginnen met 7011
SELECT 
    GC_ID,
    GC_CODE,
    GC_OMSCHRIJVING,
    GC_HISTORISCH_JN
FROM AT_KOSTSRT
WHERE GC_CODE STARTING WITH '7011'
ORDER BY GC_CODE;

-- 1b. Zoek alle codes die '7011' BEVATTEN (in geval van andere formatting)
SELECT 
    GC_ID,
    GC_CODE,
    GC_OMSCHRIJVING,
    GC_HISTORISCH_JN
FROM AT_KOSTSRT
WHERE GC_CODE CONTAINING '7011'
ORDER BY GC_CODE;

-- 2. Zoek specifiek naar 7011.30 en 7011.40
SELECT 
    GC_ID,
    GC_CODE,
    GC_OMSCHRIJVING,
    GC_HISTORISCH_JN
FROM AT_KOSTSRT
WHERE GC_CODE IN ('7011.30', '7011.40', '7011.03')
ORDER BY GC_CODE;

-- 3. Bekijk alle kostensoorten die te maken hebben met reis/km
SELECT 
    GC_ID,
    GC_CODE,
    GC_OMSCHRIJVING,
    GC_HISTORISCH_JN,
    CATEGORIE,
    TYPE_KOSTENSOORT
FROM AT_KOSTSRT
WHERE UPPER(GC_OMSCHRIJVING) CONTAINING 'REIS' 
   OR UPPER(GC_OMSCHRIJVING) CONTAINING 'KM'
   OR UPPER(GC_OMSCHRIJVING) CONTAINING 'KILOM'
   OR UPPER(GC_OMSCHRIJVING) CONTAINING 'VERBLIJF'
   OR UPPER(GC_OMSCHRIJVING) CONTAINING 'ONKOSTEN'
ORDER BY GC_CODE;

-- 3b. Zoek specifiek naar codes 100300, 100167, 100288 die nu in code gebruikt worden
SELECT 
    GC_ID,
    GC_CODE,
    GC_OMSCHRIJVING,
    GC_HISTORISCH_JN,
    CATEGORIE,
    TYPE_KOSTENSOORT
FROM AT_KOSTSRT
WHERE GC_ID IN (100300, 100167, 100288)
ORDER BY GC_ID;

-- 4. Bekijk alle KOSTSRT records (om te zien welke er zijn)
-- LET OP: Dit kan veel records opleveren!
SELECT 
    GC_ID,
    GC_CODE,
    GC_OMSCHRIJVING,
    GC_HISTORISCH_JN,
    CATEGORIE,
    TYPE_KOSTENSOORT
FROM AT_KOSTSRT
WHERE GC_HISTORISCH_JN = 'N'  -- Alleen actieve records
ORDER BY GC_CODE;

-- 4b. Tel hoeveel records er zijn
SELECT COUNT(*) as TOTAAL_KOSTSRT FROM AT_KOSTSRT;
SELECT COUNT(*) as ACTIEVE_KOSTSRT FROM AT_KOSTSRT WHERE GC_HISTORISCH_JN = 'N';

-- 5. Check welke KOSTSRT_GC_ID momenteel gebruikt wordt in AT_URENBREG
SELECT DISTINCT
    u.KOSTSRT_GC_ID,
    k.GC_CODE,
    k.GC_OMSCHRIJVING,
    COUNT(*) as AANTAL_KEER_GEBRUIKT
FROM AT_URENBREG u
LEFT JOIN AT_KOSTSRT k ON u.KOSTSRT_GC_ID = k.GC_ID
WHERE u.KOSTSRT_GC_ID IS NOT NULL
GROUP BY u.KOSTSRT_GC_ID, k.GC_CODE, k.GC_OMSCHRIJVING
ORDER BY k.GC_CODE;
