-- SQL Script om te begrijpen hoe uren worden geboekt in AT_URENBREG
-- Gebruik dit in DBeaver

-- 1. Bekijk structuur van een normale uren registratie
-- Selecteer een paar recente registraties
SELECT FIRST 10
    u.GC_ID,
    u.DOCUMENT_GC_ID,
    u.GC_REGEL_NR,
    u.DATUM,
    u.AANTAL,
    u.TAAK_GC_ID,
    t.GC_CODE as TAAK_CODE,
    t.GC_OMSCHRIJVING as TAAK_OMSCHRIJVING,
    u.WERK_GC_ID,
    w.GC_CODE as WERK_CODE,
    w.GC_OMSCHRIJVING as WERK_OMSCHRIJVING,
    u.KOSTSRT_GC_ID,
    k.GC_CODE as KOSTSRT_CODE,
    k.GC_OMSCHRIJVING as KOSTSRT_OMSCHRIJVING,
    u.GC_OMSCHRIJVING
FROM AT_URENBREG u
LEFT JOIN AT_TAAK t ON u.TAAK_GC_ID = t.GC_ID
LEFT JOIN AT_WERK w ON u.WERK_GC_ID = w.GC_ID
LEFT JOIN AT_KOSTSRT k ON u.KOSTSRT_GC_ID = k.GC_ID
WHERE u.DATUM >= '2025-01-01'
ORDER BY u.DATUM DESC, u.DOCUMENT_GC_ID DESC, u.GC_REGEL_NR;

-- 2. Bekijk specifiek Montage Uren (7011.30)
SELECT FIRST 10
    u.GC_ID,
    u.DOCUMENT_GC_ID,
    u.GC_REGEL_NR,
    u.DATUM,
    u.AANTAL,
    u.TAAK_GC_ID,
    t.GC_CODE as TAAK_CODE,
    u.WERK_GC_ID,
    w.GC_CODE as WERK_CODE,
    u.KOSTSRT_GC_ID,
    k.GC_CODE as KOSTSRT_CODE,
    u.GC_OMSCHRIJVING
FROM AT_URENBREG u
LEFT JOIN AT_TAAK t ON u.TAAK_GC_ID = t.GC_ID
LEFT JOIN AT_WERK w ON u.WERK_GC_ID = w.GC_ID
LEFT JOIN AT_KOSTSRT k ON u.KOSTSRT_GC_ID = k.GC_ID
WHERE u.TAAK_GC_ID = 100268  -- 7011.30 Montage Uren
ORDER BY u.DATUM DESC;

-- 3. Bekijk Tekenkamer (7011.40)
SELECT FIRST 10
    u.GC_ID,
    u.DOCUMENT_GC_ID,
    u.GC_REGEL_NR,
    u.DATUM,
    u.AANTAL,
    u.TAAK_GC_ID,
    t.GC_CODE as TAAK_CODE,
    u.WERK_GC_ID,
    w.GC_CODE as WERK_CODE,
    u.KOSTSRT_GC_ID,
    k.GC_CODE as KOSTSRT_CODE,
    u.GC_OMSCHRIJVING
FROM AT_URENBREG u
LEFT JOIN AT_TAAK t ON u.TAAK_GC_ID = t.GC_ID
LEFT JOIN AT_WERK w ON u.WERK_GC_ID = w.GC_ID
LEFT JOIN AT_KOSTSRT k ON u.KOSTSRT_GC_ID = k.GC_ID
WHERE u.TAAK_GC_ID = 100278  -- 7011.40 Tekenkamer
ORDER BY u.DATUM DESC;

-- 4. Bekijk alle AT_TAAK codes die beginnen met 7011
SELECT 
    GC_ID,
    GC_CODE,
    GC_OMSCHRIJVING,
    GC_HISTORISCH_JN
FROM AT_TAAK
WHERE GC_CODE STARTING WITH '7011'
ORDER BY GC_CODE;

-- 5. Bekijk hoe een document met meerdere regels eruitziet
-- (1 regel voor uren, 1 regel voor km, etc.)
SELECT FIRST 30
    u.DOCUMENT_GC_ID,
    u.GC_REGEL_NR,
    u.DATUM,
    u.AANTAL,
    t.GC_CODE as TAAK_CODE,
    w.GC_CODE as WERK_CODE,
    k.GC_CODE as KOSTSRT_CODE,
    k.GC_OMSCHRIJVING as KOSTSRT_OMSCHRIJVING,
    u.GC_OMSCHRIJVING
FROM AT_URENBREG u
LEFT JOIN AT_TAAK t ON u.TAAK_GC_ID = t.GC_ID
LEFT JOIN AT_WERK w ON u.WERK_GC_ID = w.GC_ID
LEFT JOIN AT_KOSTSRT k ON u.KOSTSRT_GC_ID = k.GC_ID
WHERE u.DOCUMENT_GC_ID IN (
    -- Zoek documenten die meerdere regels hebben
    SELECT FIRST 10 DOCUMENT_GC_ID 
    FROM AT_URENBREG 
    WHERE DATUM >= '2025-01-01'
    GROUP BY DOCUMENT_GC_ID 
    HAVING COUNT(*) > 1
)
ORDER BY u.DOCUMENT_GC_ID, u.GC_REGEL_NR;

-- 5b. Bekijk AT_URENSRT - mogelijk uresoort vs kostensoort
SELECT 
    u.GC_ID,
    u.GC_CODE,
    u.GC_OMSCHRIJVING,
    u.KOSTSRT_GC_ID,
    k.GC_CODE as KOSTSRT_CODE,
    k.GC_OMSCHRIJVING as KOSTSRT_OMSCHRIJVING,
    u.GC_HISTORISCH_JN
FROM AT_URENSRT u
LEFT JOIN AT_KOSTSRT k ON u.KOSTSRT_GC_ID = k.GC_ID
ORDER BY u.GC_CODE;

-- 6. Zoek documenten die zowel uren ALS kostensoorten hebben
SELECT FIRST 50
    u.DOCUMENT_GC_ID,
    u.GC_REGEL_NR,
    u.DATUM,
    u.AANTAL,
    t.GC_CODE as TAAK_CODE,
    k.GC_CODE as KOSTSRT_CODE,
    k.GC_OMSCHRIJVING as KOSTSRT_OMSCHRIJVING,
    u.GC_OMSCHRIJVING
FROM AT_URENBREG u
LEFT JOIN AT_TAAK t ON u.TAAK_GC_ID = t.GC_ID
LEFT JOIN AT_KOSTSRT k ON u.KOSTSRT_GC_ID = k.GC_ID
WHERE u.KOSTSRT_GC_ID IS NOT NULL
AND u.DATUM >= '2024-01-01'
ORDER BY u.DOCUMENT_GC_ID, u.GC_REGEL_NR;
